### ISSUE TITLE
Resource Database

### ISSUE THREAD

**Issue by if0ne** [GiiGaTeam/GiiGaEngine#15]
- [x] #49
- [x] #50
- [x] #51
- [x] #52
- [x] #53
- [x] #54
- [x] #55
- [x] #56

**Comment by if0ne** [comment]
[Diagram](https://www.planttext.com/?text=fLRTRzem47_FNs6fBz32onuhXChArY6D3QMfzZYP-82iYHFP3bsqxN-Vl-9ycgwQX9JptU--psVkkC1Cb5aQ17ZF1SEnG76AEKVlCOSGU5wo6BQOuYEmu5U0q5nBLfo3M6E1z_A0QaABIvep0Wp8zmmN2mtyX2b90V4JLkn2CCDMXfPBz3d718ZcS9-5g2fWXiuGYzmgQorsBVLRHwKlVpV89QE58HmMqH8zWD17IKyqiI6Id0P_Wi3a79PK95a_RQJpVfEX3oIHWVw_dOPfQ_zK9WHjI0zXwjk3ADhL3aMLqkdrs7N1X7RLqhtg5DiuMA8r5409q0Iu5nD2YWKGtOPpBksj2AdruchI7WZYsDC67aAMd-4j6jA1TTh1CiCRc7uLsnqUNRu7yvtq0Dhg8puhWImlq39hb7HDRz0M-4aJZy-GWi2fOqJmKvGCtgsDE0OAcjenEE2z9bSbIN9VvypC8zjtAK_e4Usm4C3eiFsAOVjrA6aiafmkLFoJqMivjHVp7gVf7iVFxcQDeZLqOYCei3YrYgv4ArxHk2sVeN-A0SNMVVzER6KXRNtRRToOiMjAOGhz-YYFO-fH7jP_i0DT4yZjhNKVmZ6HP6N3cAEFYGonvgh3vNqvQr9TEhKjBkfEEAdR8-hG6UkJ_WmtN3_qtk8Qosp7yX-oHD-mY4zow5xCjnEBNbJede4icjjh4SAAdA71T7GQbnKvCqbunYXYbRc-bq1F1QbzgwhNgAyfsUcXi-SlyBBJYYxlRdOoPIKQUGBHulTyxdad_FZHvo3ml3RNNeLW-FAsm-bspOCTQ_2OlWx3a-U8ZKjHUysFnJ8CMo77_em4xHsOUq3D2-Spqvx2owxq8bKGPpJeNGfVKirDhJrqvS6TN4NgJzXV)
<details><summary>Plant Uml</summary>
<p>

```
@startuml

abstract class BaseResourceManager
{
  - BaseAssetDatabase Database
  - unordered_map<AssetHandle shared_ptr<AssetBase>> LoadedAssets
  - unordered_map<AssetType, vector<AssetLoader*>> AssetLoaders
  
  + abstract AssetRef<T> GetAsset<T>(AssetId<T>)
}

class RuntimeResourceManager 
{
  AssetRef<T> GetAsset<T>(AssetId<T>)
}

class EditorResourceManager 
{
  AssetRef<T> GetAsset<T>(AssetId<T>)
}

class AssetId<T>
{
  - Uuid Id
}

class AssetHandle
{
  - Uuid Id
  - AssetType Ty
}

abstract class AssetBase 
{
  # Uuid Id
  # vector<AssetHandle> Dependenies
  # vector<AssetHandle> Related
  + void AddDependency(AssetHandle dependency)
  + void RemoveDependency(AssetHandle dependency)
  + void AddRelated(AssetHandle related)
  + void RemoveRelated(AssetHandle related)
  + abstract AssetType GetType()
  + abstract void Save()
}

enum AssetType
{
  + Mesh
  + SkeletalMesh
  + Texture2D
  + Scene
  + Prefab
  + Audio
}

abstract class AssetLoader 
{
  - string Pattern
  - AssetType Ty
  - vector<function<void(shared_ptr<AssetBase>)>> LoadCallbacks
  
  + shared_ptr<AssetBase> Load(string path)
  + void LoadAsync(string path, function<void(shared_ptr<AssetBase>)> callback)
}

class AssetMeta
{
  + AssetHandle Id
  + string Path
  + vector<AssetHandle> Dependenies
  + vector<AssetHandle> Related
}

abstract class BaseAssetDatabase
{
  - std::string RegistryPath
  - File RegistryFile
  - unordered_map<AssetHandle, AssetMeta> RegistryMap
  
  + AssetMeta GetAssetMeta(AssetHandle handle)
}

class RuntimeAssetDatabase
{
}

class EditorAssetDatabase
{
  - ProjectWatcher watcher
  
  + AssetId<T> CreateAsset<T>(T asset, string path)
  + AssetHandle ImportAsset(string path)
  + void TryRemoveAsset(string path)
  + void UpdateAssetPath(string OldPath, string NewPath)
}

class ProjectWatcher
{

}

BaseResourceManager <|-- RuntimeResourceManager
BaseResourceManager <|-- EditorResourceManager
RuntimeResourceManager *-- EditorResourceManager

BaseAssetDatabase <|-- RuntimeAssetDatabase
BaseAssetDatabase <|-- EditorAssetDatabase
RuntimeAssetDatabase *-- RuntimeResourceManager
EditorAssetDatabase *-- EditorResourceManager

RuntimeAssetDatabase *-- EditorAssetDatabase
BaseAssetDatabase *-- BaseResourceManager

AssetLoader o-- BaseResourceManager
AssetBase *-- BaseResourceManager
AssetHandle *-- BaseResourceManager

AssetType *-- AssetBase
ProjectWatcher *-- EditorAssetDatabase
AssetMeta *-- BaseAssetDatabase

@enduml

``` 

</p>
</details> 

![fLRTRzem47_FNs6fBz32onuhXChArY6D3QMfzZYP-82iYHFP3bsqxN-Vl-9ycgwQX9JptU--psVkkC1Cb5aQ17ZF1SEnG76AEKVlCOSGU5wo6BQOuYEmu5U0q5nBLfo3M6E1z_A0QaABIvep0Wp8zmmN2mtyX2b90V4JLkn2CCDMXfPBz3d718ZcS9-5g2fWXiuGYzmgQorsBVLRHwKl](https://github.com/user-attachments/assets/ef76b8a0-a8f0-4e40-b024-dcf5fa90e3ed)

- Без мета файлов
- Без бинарный/обработанных ассетов
- Файл-регистр, куда записаны все файлы проекта/игры
- ProjectWatcher следит за изменениями файлов проекте и дергает методы EditorAssetDatabase
- Может надо добавить события, чтобы потом прикрутить редактор Imgui
- Надо будет добавить в AssetMeta информацию о настройках ассета

**Comment by damibran** [comment]
> * Файл-регистр, куда записаны все файлы проекта/игры

Это точно норм? Это делает невозможным совместную работу над одним проектом с системой контроля версий.

**Comment by if0ne** [comment]
> > * Файл-регистр, куда записаны все файлы проекта/игры
> 
> 
> 
> Это точно норм? Это делает невозможным совместную работу над одним проектом с системой контроля версий.

Файл-регистр будет человекочитаемым. Он будет по аналогии с файлом-проектом из visual studio, в котором есть список всех файлов проекта, вроде при мердже особых проблем не возникает

**Comment by if0ne** [comment]
UPD 27.11
Диаграмма сопоставлена с текущим кодом
[Diagram Link](https://www.planttext.com/?text=fLPRRzem57xdLrYgLC4ABtj6KRlITfN6YYZL7gT3V2XU4pko7Jfs-U_pBOb3alPX4b9id-yxFdTpgJH8NURPQ9Hce1HPenAbJ74979vHZdwF29cHJw3mIYdK2z2mDHjIBPouv49Ib4Y_vr3C7V0pS9eXSUirxloXLPCav8i0YjITACDtAchW9Y6tZ7lfE5QrTvz91ssrlOKsluiMuGwrsvfrYyBePFItYaCa235uAXabzxIvVtCia6oEbWDRfIMacaHawonntBDOcrTnHWwOQY7ZO2LaWGLoYfoX6iIiCGEDr7bLNzlOS-U_O-SAyZ9lPCwM2x94jNUBnnVCK4DM7spmfoubVbnuSOeStMebSGTR7yUICZ7aiSkh925UHixuCrc1rYXvDsmXCseFjd0ABQCQSKaT1mq5wFt4OG_2fC3d-yZJM3vrnzUGPLj8NqWQ5fws5I8ZIz3f7bKmPsn9GNCxvqiJaX2fJjOk7CEwv0FsVWxxCLKEkt7iD5e8fhjtZS_Ce8_X_XdPcHr2NWjkMUORygGDfurhIGrUGZ7Kl3P5qvRbFhKVJFD6M_KslqNqksjZhj4PklxC9_GH3bWPDPuqvvRQT_vW0XnxFAwxN1IQ2GxPF7AtwdQx6vWGeR2kAAsIbnvRKB3hQQiUQ8sCDAmn5mVyJoNtd6a66ViLcZZCvP9hbdTgevRVK6O2srSwAob-c4n-S_KloQl_jWRZFRLpqIK7wz6uEQzCjiLt7hLXgo_oGaWVuN63cn9L06yNFMqQenEoKtu4U2fePPMj-m1woEZAtUEtN_5rrUxbjjSX5A6Y_TmmhSgasWW7YSMsfjnX1Kn8KAEggDqSaEi5Cqwwyxcr8Y4Ft59D6ONn_1RA-_q-RYaesx41e2wB3ET57OYaqSuX3oJVO_QPTrxueke-wFC_irb_bGrW-ogkZqy-MCKdVojwoBsuOOrzrtSjxTKPFrQY1z0ytttqkFg7rRjNpefhPQEJHXnoefvM3j5z44QNfetiFxP_)

<details><summary>Plant UML</summary>
<p>
@startuml

class ResourceManager
{
  - BaseAssetDatabase Database
  - unordered_map<AssetHandle AssetRef<AssetBase>> LoadedAssets
  
  - AssetRef<T> FindAsset(AssetHandle handle)
  - AssetRef<T> LoadAsset(AssetHandle handle)
  
  + AssetRef<T> GetAsset<T>(AssetHandle id)
}

class AssetHandle
{
  - Uuid Id
  - AssetType Ty
}

abstract class AssetBase 
{
  # AssetHandle Id
  # vector<AssetHandle> Dependenies
  # vector<AssetHandle> Related
  + abstract AssetType GetType()
}

enum AssetType
{
  + Mesh
  + SkeletalMesh
  + Texture2D
  + Scene
  + Prefab
  + Audio
}

abstract class AssetLoader 
{
  - string Pattern
  - AssetType Ty
  
  + shared_ptr<AssetBase> Load(string path)
  + void LoadAsync(string path, LoadCallback callback)
  + bool MatchesPattern(path path)
}

class AssetMeta
{
  + AssetHandle Id
  + path Path
  + vector<AssetHandle> Dependenies
  + vector<AssetHandle> Related
}

abstract class BaseAssetDatabase
{
  - path RegistryPath
  - fstream RegistryFile
  - map<AssetHandle, AssetMeta> RegistryMap
  - unordered_map<AssetType, vector<AssetLoader*>> AssetLoaders
  - unordered_map<AssetType, AssetLoader*> AssetCreators
  
  # void SaveRegistry()
  # void LoadRegistry()
  # void OpenRegistryFile()
  
  + optional<AssetMeta> GetAssetMeta(AssetHandle handle)
  + void AddDependency(AssetHandle asset, AssetHandle dependency)
  + void RemoveDependency(AssetHandle asset, AssetHandle dependency)
  + void Initialize()
}

class RuntimeAssetDatabase
{
}

class EditorAssetDatabase
{
  - ProjectWatcher watcher
  
  + AssetId<T> CreateAsset<T>(T& asset, path& path)
  + AssetHandle ImportAsset(path& path, span<AssetHandle> dependenies)
  + void RemoveAsset(path& path)
  + void UpdateAssetPath(path& OldPath, path& NewPath)
}

class ProjectWatcher
{
  - vector<string> DirsToWatch
  - vector<FileWatch<string>> Watchers
  
  + EventDispatcher<path> OnFileAdded
  + EventDispatcher<path> OnFileRemoved
  + EventDispatcher<path> OnFileModified
  + EventDispatcher<tuple<path, path>> OnFileRenamed
  + void StartWatch()
}

BaseAssetDatabase <|-- RuntimeAssetDatabase
BaseAssetDatabase <|-- EditorAssetDatabase
RuntimeAssetDatabase *-- ResourceManager
EditorAssetDatabase *-- ResourceManager

RuntimeAssetDatabase *-- EditorAssetDatabase
BaseAssetDatabase *-- ResourceManager

AssetLoader o-- ResourceManager
AssetBase *-- ResourceManager
AssetHandle *-- ResourceManager

AssetType *-- AssetBase
ProjectWatcher *-- EditorAssetDatabase
AssetMeta *-- BaseAssetDatabase

@enduml
</p>
</details>
