### ISSUE TITLE
Window

### ISSUE THREAD

**Issue by if0ne** [GiiGaTeam/GiiGaEngine#24]
- [ ] Реализовать event dispatcher

Нерешенные вопросы:

- [x] Должен ли _Swapchain (IDXGISwapchain)_ хранится в Window или он должен хранится в Render System? 
[Ответ](https://github.com/GiiGaTeam/GiiGaEngine/issues/24#issuecomment-2444068285)
- [x] Для окна используем WinAPI, glfw, SDL?
SDL

**Comment by damibran** [comment]
> * Должен ли _Swapchain (IDXGISwapchain)_ хранится в Window или он должен хранится в Render System?

Хранить Swapchain (SC) в window кмк нет большого смысла, для создания SC нужен device (queue), соответственно либо создание всего окна должно происходить после RenderSystem (или только device), либо это должно быть отложенное создание SC (window->RenderSystem->window.SC), после которого также нужно прокинуть референсы на SC в RenderSystem, поскольку он там активно используется. Проще сделать (window->RenderSystem).

Тогда вопрос такой:
Нормально ли просто передавать Window при создании RenderSystem?

**Comment by if0ne** [comment]
> Нормально ли просто передавать Window при создании RenderSystem?

Да, т.к. RenderSystem должна подписаться на ResizeWindowEvent у Window
