### ISSUE TITLE
Render Buffers

### ISSUE THREAD

**Issue by if0ne** [GiiGaTeam/GiiGaEngine#64]
Нерешенные вопросы:
- [x] Нужно ли разделять буферы на Constant, Vertex, Index и т.д. или один класс будет обрабатывать все случаи?
Один класс

<details><summary>UML</summary>
@startuml

class GPULocalResource 
{
    + GPULocalResource(RenderDevice, shared_ptr<ID3D12Resource> resource, initialState)
    + GPULocalResource(RenderDevice, D3D12_RESOURCE_DESC, initialState

    + void UpdateContents(void* data, dataSize)
    + StateTransition(IRenderContext, stateAfer)

    +BufferView<Constant> GetViewByDesc(D3D12_CONSTANT_BUFFER_VIEW_DESC)
    +BufferView<ShaderResource> GetViewByDesc(D3D12_SHADER_RESOURCE_VIEW_DESC)
    +BufferView<UnorderedAccess> GetViewByDesc(D3D12_UNORDERED_ACCESS_VIEW_DESC)
    +BufferView<RenderTarget> GetViewByDesc(D3D12_RENDER_TARGET_VIEW_DESC)
    +BufferView<DepthStencil> GetViewByDesc(D3D12_DEPTH_STENCIL_VIEW_DESC)
    +BufferView<Index> GetViewByDesc(D3D12_INDEX_BUFFER_VIEW)
    +BufferView<Vertex> GetViewByDesc(D3D12_VERTEX_BUFFER_VIEW)

    +shared_ptr<BufferView<Constant>> GetViewFirstConstant()
    +shared_ptr<BufferView<ShaderResource>> GetViewFirstShaderResource()
    +shared_ptr<BufferView<UnorderedAccess>> GetViewFirstUnorderedAccess()
    +shared_ptr<BufferView<RenderTarget>> GetViewFirstRenderTarget()
    +shared_ptr<BufferView<DepthStencil>> GetViewFirstDepthStencil()
    +shared_ptr<BufferView<Index>> GetViewFirstIndex()
    +shared_ptr<BufferView<Vertex>> GetViewFirstVertex()

    +BufferView<Constant> CreateConstantBufferView(D3D12_CONSTANT_BUFFER_VIEW_DESC)
    +BufferView<ShaderResource> CreateShaderResourceBufferView(D3D12_SHADER_RESOURCE_VIEW_DESC&)
    +BufferView<UnorderedAccess> CreateUnorderedAccessView(ID3D12Resource* counterBuffer,
    +    D3D12_UNORDERED_ACCESS_VIEW_DESC&)
    +BufferView<RenderTarget> CreateRenderTargetView(D3D12_RENDER_TARGET_VIEW_DESC*)
    +BufferView<DepthStencil> CreateDepthStencilView(D3D12_DEPTH_STENCIL_VIEW_DESC&)
    +BufferView<Index> CreateIndexBufferView(D3D12_INDEX_BUFFER_VIEW)
    +BufferView<Vertex> CreateVetexBufferView(D3D12_VERTEX_BUFFER_VIEW)

    - shader_ptr<Resource> resource
    - D3D12_RESOURCE_STATES currentState
    - unordered_map constantViews_;
    - unordered_map shaderResourceViews_;
    - unordered_map unorderedAccessViews_;
    - unordered_map renderTargetViews_;
    - unordered_map depthStencilViews_;
    - unordered_map indexViews_;
    - unordered_map vertexViews_;
}

class BufferView <<ViewType>>
{
    - ViewType::ViewHolder holder_

    + BufferView(typename ViewType::ViewHolder&& descriptor_holder)
    + const ViewType::ViewHolder& getDescriptor()
}

class ViewType
{

}

class Constant
{
    ViewHolder DesciptorHandles
    ViewDesc D3D12_CONSTANT_BUFFER_VIEW_DESC
}

class ShaderResource
{
    ViewHolder DesciptorHandles
    ViewDesc D3D12_SHADER_RESOURCE_VIEW_DESC
}

class UnorderedAccess
{
    ViewHolder DesciptorHandles
    ViewDesc D3D12_UNORDERED_ACCESS_VIEW_DESC
}

class RenderTarget
{
    ViewHolder DescriptorHeapAllocation
    ViewDesc D3D12_RENDER_TARGET_VIEW_DESC
}

class DepthStencil
{
    ViewHolder DescriptorHeapAllocation
    ViewDesc D3D12_DEPTH_STENCIL_VIEW_DESC
}

class Vertex
{
    ViewHolder D3D12_VERTEX_BUFFER_VIEW
    ViewDesc D3D12_VERTEX_BUFFER_VIEW
}

class Index
{
    ViewHolder D3D12_INDEX_BUFFER_VIEW
    ViewDesc D3D12_INDEX_BUFFER_VIEW
}

ViewType --|> Constant
ViewType --|> ShaderResource
ViewType --|> UnorderedAccess
ViewType --|> RenderTarget
ViewType --|> DepthStencil
ViewType --|> Vertex
ViewType --|> Index

Constant .. BufferView
ShaderResource .. BufferView
UnorderedAccess .. BufferView
RenderTarget .. BufferView
DepthStencil .. BufferView
Vertex .. BufferView
Index .. BufferView

BufferView .. GPULocalResource

note as GPULocalResource_GPULocalResourceNote
GPULocalResource (RenderDevice device, D3D12_RESOURCE_FLAGS resourceFlags):
    heapProperties = CD3DX12_HEAP_PROPERTIES(D3D12_HEAP_TYPE_DEFAULT);
    buffer = device->CreateCommittedResource(&heapProperties, D3D12_HEAP_FLAG_NONE,
            &resourceDesc,
            D3D12_RESOURCE_STATE_COPY_DEST)
end note

note as D3D12_HEAP_TYPE
    D3D12_HEAP_TYPE_DEFAULT:
        GPU-local memory, generally the fastest for GPU operations.
        Used for resources that don’t need to be accessed by the CPU frequently.
        Ideal for textures, vertex buffers, index buffers, and other large resources.
end note

D3D12_HEAP_TYPE .. GPULocalResource_GPULocalResourceNote
GPULocalResource_GPULocalResourceNote .. GPULocalResource::GPULocalResource

@enduml
</details> 

![image](https://github.com/user-attachments/assets/006c8926-e688-4f13-babf-d210d62257ff)

**Comment by damibran** [comment]
review request

**Comment by if0ne** [comment]
Судя по диаграмме это общий класс для всех буферов. Я бы сделал enum BufferType, который будет использоваться для создания конкретного типа-буфера. В зависимости от этого в конструкторе (или инициализаторе) будет выбираться куча, флаги и начальный ResourceState.

Для constant-буферов подходит Upload куча, которая шарится между GPU и CPU, и в этот буфер можно писать данные без промежуточного буфера. Не знаю насколько разница в перформансе будет, но я думаю Upload-а для константых буферов будет достаточно. Так же можно использовать [SetGraphicsRoot32BitConstants](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setgraphicsroot32bitconstants), если хочется прям перформанса. Вроде при создании буфера в Upload куче нужно ставить начальное состояние GenericRead.

Я бы еще в буфер (и в текстуру в дальнейшем) добавил текущее состояние ResourceState, чтобы проще было делать барьеры - нам нужно будет только знать в какое состояние мы хотим перейти.

Насчет двойных дескрипторов. Я бы перенес эту логику в DescriptorAllocator / DescriptorHeap - если создается DescriptorHeap с ShaderVisibility, то нужно будет создавать и вторую кучу без ShaderVisibility, и все операции дублируются на эти кучи.

**Comment by damibran** [comment]
> В зависимости от этого в конструкторе (или инициализаторе) будет выбираться куча, флаги и начальный ResourceState.

Согласен только с флагами и то только из-за `D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS`

> Для constant-буферов подходит Upload куча, которая шарится между GPU и CPU, и в этот буфер можно писать данные без промежуточного буфера.

Не вижу смысла использовать другой тип кучи. Идея такая, что этот класс будет использоваться для статических объектов (константных буфферов тоже почему нет). Upload куча будет использоваться в одном для каждого фрейма UploadBuffer'е динамических данных. Если пользователь хочет каждый кадр обновлять (пометив его динамическим) загрузка таких должна быть постоянной с использованием UploadBuffer, с создаваемыми в него дескрипторами с использованием `DynamicSuballocationsManager` #95.

Поддержка GraphicsRoot32BitConstants также может быть реализована только уже в PerObjectData или ShaderResouce #81.

> добавил текущее состояние ResourceState

Согласен.

> и все операции дублируются на эти кучи.

Тут все не так просто, размер CPU кучи дескрипторов не ограничен (или их количество), на GPU размер ограничен и хочется иметь только одну для скорости. Хотя в текущей имплементации и это не учтено... 

Допустим если и сделать так, все равно требуется отслеживать занятость дескриптора в обеих кучах (за что и отвечает DescriptorHeapAllocation), при освобождении ресурса, нужно освобождать его из обеих куч.

А если делать работать с проблемой описанной выше также нужно поддерживать возможность освобождения только дескриптора в GPU куче (чисто из-за стоимости операций выделения и освобождения _там что-то типо log(n)_). 
Можно как вариант вынести эти два объекта DescriptorHeapAllocation, в отдельный класс.

В общем за подробностями см. #95, я сделал commit.

**Comment by if0ne** [comment]
> Не вижу смысла использовать другой тип кучи.

Я думал UploadBuffer будет подклассом этого класса. Судя по названию это GPU-only, так что ладно, тип кучи можно не менять. 

> А если делать работать с проблемой описанной выше также нужно поддерживать возможность освобождения только дескриптора в GPU куче 

Мне кажется, что случаев с освобождением только из одной кучи не будет. Можешь привести пример?

**Comment by if0ne** [comment]
> Согласен только с флагами и то только из-за `D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS`

Тут можно обойтись bool-ом.

**Comment by damibran** [comment]
> Я думал UploadBuffer будет подклассом этого класса

Да, не будет. Я планировал использовать готовую реализацию. [3dgep UploadBuffer](https://github.com/jpvanoosten/LearningDirectX12/blob/49eb021f6a6f538e3b6001fd8f9b7108d2900751/DX12Lib/inc/dx12lib/UploadBuffer.h#L46)

> Можешь привести пример?

Ну вот как раз какая-то очень странная ситуация, что в GPU куче закончилось место, но тебе нужно запихнуть туда новый дескриптор. Ты можешь освободить только его, оставив CPU.

Как бы возможно я не правильно понимаю причины такого дизайна в [DiligentEngine](https://web.archive.org/web/20230811105754/http://diligentgraphics.com/diligent-engine/architecture/d3d12/managing-descriptor-heaps/).

Возможно за освобождения только GPU дескриптора отвечает их [Shader Resource Cache](https://web.archive.org/web/20220908011911/https://diligentgraphics.com/diligent-engine/architecture/d3d12/shader-resource-cache/). Я не исследовал его еще, да и не собирался делать его у нас)

**Comment by if0ne** [comment]
> > Я думал UploadBuffer будет подклассом этого класса
> 
> Да, не будет. Я планировал использовать готовую реализацию. [3dgep UploadBuffer](https://github.com/jpvanoosten/LearningDirectX12/blob/49eb021f6a6f538e3b6001fd8f9b7108d2900751/DX12Lib/inc/dx12lib/UploadBuffer.h#L46)
> 
> > Можешь привести пример?
> 
> Ну вот как раз какая-то очень странная ситуация, что в GPU куче закончилось место, но тебе нужно запихнуть туда новый дескриптор. Ты можешь освободить только его, оставив CPU.
> 
> Как бы возможно я не правильно понимаю причины такого дизайна в [DiligentEngine](https://web.archive.org/web/20230811105754/http://diligentgraphics.com/diligent-engine/architecture/d3d12/managing-descriptor-heaps/).
> 
> Возможно за освобождения только GPU дескриптора отвечает их [Shader Resource Cache](https://web.archive.org/web/20220908011911/https://diligentgraphics.com/diligent-engine/architecture/d3d12/shader-resource-cache/). Я не исследовал его еще, да и не собирался делать его у нас)

Странная архитектура. По моему мнению, Non Shader-Visible CbvSrvUav меньше встречаются, чем ShaderVisible. Зачем давать возможность неограниченно аллоцировать на CPU, но иметь ограничение на GPU. Как-то переусложнено, ну ладно, я понял.
